eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://localhost:9091/
  server:
    wait-time-in-ms-when-sync-empty: 3000
server:
  port: 9091
#spring:
#  application:
#    name: EmployeeEurekaServer


